page_title: "CrewAI : Empowering Intelligent Agents"
llm_options:
  - "Groq"
usecase_options:
  - "Chatbot with Tool"
groq_model_options:
  - "mixtral-8x7b-32768"
  - "llama3-8b-8192"
  - "llama3-70b-8192"
  - "gemma-7b-i"

